spring:
  application:
    name: Ai-Services
  data:
    uri: mongodb://localhost:27017/Activity_db
    database: Activity_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8046



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: fitness.exchange
  routing:
    key: activity.routing


gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
